name: 'Debugging with zerotier'
description: 'Debug your GitHub Actions Environment interactively by using zerotier'
author: 'Conight Wang'
runs:
  using: 'node12'
  main: 'lib/index.js'
inputs:
  sudo:
    description: 'If apt should be executed with sudo or without'
    required: false
    default: 'true'
  network:
    description: 'Zerotier network ID'
    required: true
